### ISSUE TITLE
Did you loose the http://sciencetoolbox.org domain?

### ISSUE THREAD

**Issue by dlebauer** [ScienceToolbox/sciencetoolbox#23]
Pages resolve in Japanese, links to this url from repository and README are broken.

**Comment by yht** [comment]
http://web.archive.org/web/20160109162055/http://sciencetoolbox.org/
Just get the link from web archive. It's seem latest active.

**Comment by jure** [comment]
Yes the domain expired as the product was unfortunately discontinued in the beginning of this year: https://twitter.com/juretriglav/status/697754558051786753

https://twitter.com/ScienceToolbox

I'll update the README to reflect this. Thank you!
